### ISSUE TITLE
Tildes en el XML

### ISSUE THREAD

**Issue by Gino-Loja** [UTC1992/SriSignXml#1]
Al momento de Mandar el Json y si cualquier campo tiene tildes se genera un error. 
Supongo por que no se esta codificando en UTF-8

**Comment by UTC1992** [comment]
es raro puede ser que no lo haya probado con tildes lo voy a revisar

**Comment by wirjag** [comment]
hola me podrias ayudar e estado probando tu proyecto pero en un servidor local en ubuntu funciona bien me auoriza la factura en modo prueba  trato de recrear el proyecto en un servidor web pero ya no me funciona

**Comment by wirjag** [comment]
ERROR:root:Error to send xml for reception: The AsyncTransport is based on the httpx module
Exception ignored in: <function Transport.__del__ at 0x7f4ccb1317e0>
Traceback (most recent call last):
  File "/home/willian/.local/lib/python3.10/site-packages/zeep/transports.py", line 159, in __del__
    if self._close_session:
AttributeError: 'AsyncTransport' object has no attribute '_close_session' 

![Image](https://github.com/user-attachments/assets/fbd7666d-b8f3-43a2-8eb1-1c036b5f5ada)

**Comment by wirjag** [comment]
![Image](https://github.com/user-attachments/assets/d8acb474-5a5f-4f13-91d9-7895ad676773) en mi entorno virtual si funciona e tratado de recrear en linea con docker y de la misma manera y no e podido

**Comment by Gino-Loja** [comment]
Saludos para no tener problemas con tildes usa:
`# -*- coding: utf-8 -*-`
al principio del archivo python. !Pon en donde entran los datos
Ojo solo para sistemas linux
ahora para este error:

> ERROR:root:Error to send xml for reception: The AsyncTransport is based on the httpx module Exception ignored in: <function Transport.**del** at 0x7f4ccb1317e0> Traceback (most recent call last): File "/home/willian/.local/lib/python3.10/site-packages/zeep/transports.py", line 159, in **del** if self._close_session: AttributeError: 'AsyncTransport' object has no attribute '_close_session'
> 
> ![Image](https://github.com/user-attachments/assets/fbd7666d-b8f3-43a2-8eb1-1c036b5f5ada)

Estas usando algun proxy en tus contenedores?
Me dio ese error por que estaba usando proxy.

**Comment by wirjag** [comment]
no estoy utilizando proxy

**Comment by UTC1992** [comment]
@Gino-Loja voy a actualizar el repositorio con esa solución gracias

**Comment by UTC1992** [comment]
@wirjag osea en docker ena local te funciona bien ?
Si te funciona bien en tu equipo local debería funcionar igual en un servidor como railway u otro ya que por eso de dockeriza para evitar estos problemas en el deploy.

**Comment by UTC1992** [comment]
# -*- coding: utf-8 -*-
esto se necesita en versiones de python 2 
no se necesita en versiones de python 3
por ello no lo voy añadir
